name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd my-subfolder # Si package.json está en una subcarpeta
          npm install
      - name: Run tests
        run: |
          cd my-subfolder # Si los tests están en una subcarpeta
          npm test
